### ISSUE TITLE
Create uSeoToolkit group upon installation

### ISSUE THREAD

**Issue by patrickdemooij9** [patrickdemooij9/uSeoToolkit.Umbraco#16]
Currently the user has to add the uSeoToolkit section to one of their existing groups. It would be nice if we generate a group for them with the section already in place. They can still delete it then afterwards.

**Comment by leekelleher** [comment]
I'm wondering whether the "uSeoToolkit" section should **also** be added to the "admin" user-group too? 🤔 
That way, if an admin has installed the package, they'll see the section immediately.

...or should the current user be assigned to the new "uSeoToolkit" user-group? 🤔

**Comment by patrickdemooij9** [comment]
> I'm wondering whether the "uSeoToolkit" section should **also** be added to the "admin" user-group too? 🤔 That way, if an admin has installed the package, they'll see the section immediately.
> 
> ...or should the current user be assigned to the new "uSeoToolkit" user-group? 🤔

I think adding access for the section to the admin user-group (if it exists of course) would be best for now. Not quite sure how we would assign it to the current user. They are always able to change the setup afterward anyway.
